// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bhdtqflfpkcekotecbck.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJoZHRxZmxmcGtjZWtvdGVjYmNrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkzODk0MjAsImV4cCI6MjA2NDk2NTQyMH0.bUff8DQcU6oC_vyJNZezmP-4q_6ZM0cyubqMkr8tR0w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);